# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies (Core)
      run: dotnet restore
      working-directory: src/Core

    - name: Build (Core)
      run: dotnet build --no-restore
      working-directory: src/Core

    - name: Restore dependencies (GUI)
      run: dotnet restore
      working-directory: src/GUI

    - name: Build (GUI)
      run: dotnet build --no-restore
      working-directory: src/GUI

    - name: Restore dependencies (Core.Tests)
      run: dotnet restore
      working-directory: tests/Core.Tests

    - name: Test (Core.Tests)
      run: dotnet test
      working-directory: tests/Core.Tests

    - name: Restore dependencies (GUI.Tests)
      run: dotnet restore
      working-directory: tests/GUI.Tests

    - name: Test (GUI.Tests)
      run: dotnet test
      working-directory: tests/GUI.Tests
