# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

      # Source:
    - name: Restore dependencies (ProfHeat.Core)
      run: dotnet restore
      working-directory: src/ProfHeat.Core

    - name: Build (ProfHeat.Core)
      run: dotnet build --no-restore
      working-directory: src/ProfHeat.Core

    - name: Restore dependencies (ProfHeat.AUI)
      run: dotnet restore
      working-directory: src/ProfHeat.AUI

    - name: Build (ProfHeat.AUI)
      run: dotnet build --no-restore
      working-directory: src/ProfHeat.AUI

      # Tests:
    - name: Restore dependencies (ProfHeat.Core.Tests)
      run: dotnet restore
      working-directory: tests/ProfHeat.Core.Tests

    - name: Test (ProfHeat.Core.Tests)
      run: dotnet test
      working-directory: tests/ProfHeat.Core.Tests

    - name: Restore dependencies (ProfHeat.AUI.Tests)
      run: dotnet restore
      working-directory: tests/ProfHeat.AUI.Tests

    - name: Test (ProfHeat.AUI.Tests)
      run: dotnet test
      working-directory: tests/ProfHeat.AUI.Tests
